# Generated by Django 5.2.15 on 2026-06-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'managed': False},
        ),
    ]
