# Generated by Django 5.2.15 on 2026-07-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
    ]
