# Generated by Django 5.2.15 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'day_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RouteItem',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_order', models.IntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('preference', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'trip_preference',
                'managed': False,
            },
        ),
    ]
